version: "3.9"
services:
  webapi:
    build:
      context: .
      dockerfile: MusicDownloader/Dockerfile
    environment:
      - ASPNETCORE_URLS=http://+:80
#      - ASPNETCORE_URLS=https://+:443;http://+:80
#      https://learn.microsoft.com/en-us/aspnet/core/security/docker-https?view=aspnetcore-7.0
#      - ASPNETCORE_Kestrel__Certificates__Default__Password=<DEFAULT_DEV_PASSWORD>
#      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
#    volumes:
#      - "~/.aspnet/https:/https/"
    ports:
      - '8082:80'
#      - '3501:443'
    restart: "always"