version: "3.9"
services:
  webapi:
    build:
      context: .
      dockerfile: MusicDownloader/Dockerfile
      args:
        PORTAINER_SSH_KEY: ${PORTAINER_SSH_KEY} # from .env file
    environment:
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8082:80"
    restart: "always"
    env_file: stack.env